services:
  mongo1:
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network


  api-db:
    build:
      context: ./api-db
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mongodb://mongo1:27017/wallet?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - app-network
    depends_on:
      - mongo1
      - mailhog

  api-client:
    build:
      context: ./api-client
      dockerfile: Dockerfile
    environment:
      API_DB_URL: http://api-db:3001
    ports:
      - "3002:3002"
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

volumes:
  mongo1_data:

networks:
  app-network: